package net.dreamlu.easy.model;

import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;
import net.dreamlu.easy.model.base.BaseOptions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Options extends BaseOptions<Options> {
	public static final Options dao = new Options();

	private static final String CACHE_NAME = "options";

	/**
	 * 根据name查找Options
	 * @param key 字典名
	 * @return Options
	 */
	public Options findByKey(String key) {
		String sql = "SELECT * FROM t_options WHERE `key` = ?";
		return findFirst(sql, key);
	}

	/**
	 * 根据name直接查找value
	 * @param key 字典名
	 * @return value值
	 */
	public String loadVueByKey(final String key) {
		Options options = CacheKit.get(CACHE_NAME, key, new IDataLoader() {
			@Override
			public Object load() {
				return findByKey(key);
			}
		});
		return null == options ? null : options.getValue();
	}

	/**
	 * 根据key删除指定的字典
	 * @param key
	 */
	public void removeByKey(String key) {
		CacheKit.remove(CACHE_NAME, key);
	}

	/**
	 * 更新后删除缓存
	 */
	@Override
	protected void onUpdateAfter() {
		removeByKey(this.getKey());
	}

	/**
	 * 删除后删除缓存
	 */
	@Override
	protected void onDeleteAfter() {
		removeByKey(this.getKey());
	}
}
