package net.dreamlu.easy.model;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;
import net.dreamlu.easy.model.base.BaseUser;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	private static final String CACHE_NAME = "session";

	/**
	 * 从缓存中加载用户
	 * @param userId
	 * @return
	 */
	public User loadInSession(String userId) {
		if (StrKit.isBlank(userId)) {
			return null;
		}
		return loadInSession(Integer.valueOf(userId));
	}

	/**
	 * 从缓存中加载用户
	 * @param userId
	 * @return
	 */
	public User loadInSession(final int userId) {
		return CacheKit.get(CACHE_NAME, userId, new IDataLoader() {

			@Override
			public Object load() {
				return findById(userId);
			}
		});
	}

	/**
	 * 用户的统一处理
	 */
	@Override
	public boolean save() {
		this.setCreateTime(new Date());
		return super.save();
	}

	// 用户登录
	public User findByEmail(String email){
		return this.findFirst("select * from user where email = ? and email_verify = 1 and del_status = 0 limit 1", email);
	}

}
