package net.dreamlu.easy.commons.generator;

import com.jfinal.plugin.activerecord.generator.ModelGenerator;

/**
 * Created by L.cm on 2016/7/5.
 */
public class EasyModelGenerator extends ModelGenerator {
    public EasyModelGenerator(String modelPackageName, String baseModelPackageName, String modelOutputDir) {
        super(modelPackageName, baseModelPackageName, modelOutputDir);

        this.classDefineTemplate =
                "/**%n" +
                " * Generated by Easy4JFinal.%n" +
                " */%n" +
                "@SuppressWarnings(\"serial\")%n" +
                "public class %s extends %s<%s> {%n";
    }
}
