package net.dreamlu.easy.model.base;

import com.jfinal.plugin.activerecord.IBean;
import net.dreamlu.easy.commons.base.EasyModel;

/**
 * Generated by Easy4JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOptions<M extends BaseOptions<M>> extends EasyModel<M> implements IBean {

	public void setOptionId(java.lang.Integer optionId) {
		set("optionId", optionId);
	}

	public java.lang.Integer getOptionId() {
		return get("optionId");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}

	public java.lang.String getKey() {
		return get("key");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

}
